#!/bin/sh
# ==============================================================================
# Run logging cli
# ==============================================================================

echo "Waiting for the Home Assistant CLI to be ready..."

i=0
while [ ! "$(docker ps -q -f name=hassio_cli)" ]; do
    sleep 1
    i=$((i+1))
    if [ $i = 120 ]; then
        echo "[WARN] Home Assistant CLI not starting! Jump into emergency console..."
        exec /bin/ash -l
    fi
done





hacs() {
    local hacs_dir="/mnt/data/supervisor/homeassistant/custom_components/hacs/"
    if [ ! -d "$hacs_dir" ]; then
        local attempts=0
        local max_attempts=30
        local github_url="https://github.com/hacs/integration/releases/latest/download/hacs.zip"
        local github="https://github.com"
        mkdir -p "$hacs_dir"
        while [ $attempts -lt $max_attempts ]; do
            http_status=$(curl -s -o /dev/null -w "%{http_code}" "$github")
            if [ $http_status -eq 200 ]; then
                rm -rf "$hacs_dir"/*
                curl --retry 5 --retry-connrefused -C - -L -o "${hacs_dir}hacs.zip" "$github_url" && cd "$hacs_dir" && unzip hacs.zip && rm -rf hacs.zip
                docker restart homeassistant
                sleep 5
                break
            else
                attempts=$((attempts + 1))
                echo "Attempt $attempts: GitHub returned HTTP status $http_status. Retrying in 5 seconds..."
                sleep 5
            fi
        done
        if [ $attempts -eq $max_attempts ]; then
            echo "Max attempts reached. Exiting..."
        fi
    else
        echo "HACS directory already exists. Nothing to do."
    fi






docker container exec \
    -ti hassio_cli \
    /usr/bin/cli.sh

case $? in
  10)
    # Jump to root login shell (login command)
    exec /bin/ash -l
    ;;
  143)
    # 143 graceful termination (SIGTERM). Most likely a proper shutdown.
    # Just sleep for a while until actual systemd shutdown gets invoked.
    echo ""
    echo "Home Assistant CLI has been terminated."
    sleep 30
    ;;
  *)
    echo "HA CLI failed with error code: $?"
    ;;
esac
