name: "Run command in HAOS build container"
description: "Run Home Assistant OS make in a build container with retry support"
inputs:
  image:
    description: "HAOS builder image to use"
    required: true
  target:
    description: "Build target to pass to make"
    required: true
runs:
  using: "composite"
  steps:
    - name: Execute build with retry
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.image }}" "${{ inputs.target }}"
