name: "Run command in HAOS build container"
inputs:
  image:
    description: "HAOS builder image to use"
    required: true
  target:
    description: "Target to build"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run build inside container"
      shell: bash
      run: |
        echo "🧱 Building target: ${{ inputs.target }}"
        docker run --rm --privileged \
          -e BUILDER_UID="$(id -u)" \
          -e BUILDER_GID="$(id -g)" \
          -v "${GITHUB_WORKSPACE}:/build" \
          -v "/mnt/cache:/cache" \
          -v "/mnt/output:/build/output" \
          ${{ inputs.image }} \
          bash -c '
            sleep $((RANDOM % 600))
            max_retries=3
            count=0
            CPU_CORES=$(nproc)
            JOBS=$((CPU_CORES + 1))
            until make -j${JOBS} "${{ inputs.target }}"; do
              count=$((count + 1))
              if [ $count -ge $max_retries ]; then
                echo "❌ Build failed after $count attempts."
                exit 1
              fi
              echo "⚠️  Build failed. Retrying in 30s... (Attempt $count/$max_retries)"
              sleep 30
            done
          '
