#!/bin/sh
# ==============================================================================
# Home Assistant OTA + HACS background installer launcher
# ==============================================================================

echo -e "OTA service kindly sponsored by Coolkit: \033[32mhttps://www.coolkit.cn/\033[0m"
echo -e "Official Website: \033[32mhttps://www.hasscn.top\033[0m"
echo -e "Home Assistant CLI not ready yet! Waiting..."
run_shell() { exec /bin/ash -l; }
interrupt() { echo " cancelled"; systemctl reset-failed "ha-cli@*"; run_shell; }
emergency_shell() {
    printf "\n\n[WARNING] Home Assistant CLI is not starting or was interrupted.\n"
    echo ""
    echo "This happens when start of all services takes longer than expected, or because"
    echo "of slow internet connection. Emergency console has been started, you can use"
    echo "for example the following commands for troubleshooting:"
    echo ""
    echo " * 'docker ps -a' - e.g. to check if 'hassio_supervisor' container is running"
    echo " * 'journalctl -e' - to investigate latest system logs"
    echo " * 'exit' or Ctrl+D - to exit the emergency console and retry HA CLI startup"
    echo ""
    run_shell
}

trap interrupt INT

printf "Waiting for the Home Assistant CLI to be ready..."

i=0
while [ ! "$(docker ps -q -f name=hassio_cli)" ]; do
    sleep 1
    if [ $((i % 4)) = 0 ]; then
        printf "\010\010\010   \010\010\010"
    else
        printf "."
    fi
    i=$((i+1))
    if [ $i = 600 ]; then
        emergency_shell
    fi
done

hacs() {
    echo "Installing HACS China..."
    local hacs_dir="/mnt/data/supervisor/homeassistant/custom_components/hacs/"
    local hacs_url="https://ota.hasscn.top/hacs.zip"
    mkdir -p "$hacs_dir"
    rm -rf "$hacs_dir"/*

    if curl --retry 5 --retry-connrefused -C - -L -o "${hacs_dir}hacs.zip" "$hacs_url"; then
        cd "$hacs_dir" && unzip -oq hacs.zip && rm -f hacs.zip
        docker restart homeassistant
        echo "HACS installed successfully!"
    else
        echo "[ERROR] Failed to download HACS package."
    fi
}

if curl -fs --max-time 3 https://version.hasscn.top/online.txt?install=1 >/dev/null 2>&1 &&  [ ! -f /mnt/data/supervisor/homeassistant/custom_components/hacs/base.py ]; then
    hacs >/dev/null 2>&1 &
fi



docker container exec \
    -ti hassio_cli \
    /usr/bin/cli.sh

case $? in
  10)
    # Jump to root login shell (login command)
    run_shell
    ;;
  130)
    # 130 is CLI termination with Ctrl+C (SIGINT)
    printf "\nHome Assistant CLI has been interrupted.\n"
    systemctl reset-failed "ha-cli@*"
    ;;
  143)
    # 143 graceful termination (SIGTERM). Most likely a proper shutdown.
    # Just sleep for a while until actual systemd shutdown gets invoked.
    printf "\nHome Assistant CLI has been terminated.\n"
    ;;
  *)
    printf "\nHA CLI failed with error code: %s\n" "$?"
    ;;
esac