#!/bin/sh
# ==============================================================================
# Home Assistant OTA + HACS background installer launcher
# ==============================================================================

echo -e "OTA service kindly sponsored by Coolkit: \033[32mhttps://www.coolkit.cn/\033[0m"
echo -e "Official Website: \033[32mhttps://www.hasscn.top\033[0m"
echo -e "Home Assistant CLI not ready yet! Waiting..."
# Wait for hassio_cli to be ready
i=0
while [ ! "$(docker ps -q -f name=hassio_cli)" ]; do
    sleep 1
    i=$((i+1))
    if [ $i = 600 ]; then
        echo "[WARN] Home Assistant CLI not starting! Jump into emergency console..."
        exec /bin/ash -l
    fi
done

hacs() {
    echo "Installing HACS China..."
    local hacs_dir="/mnt/data/supervisor/homeassistant/custom_components/hacs/"
    local hacs_url="https://ota.hasscn.top/hacs.zip"
    mkdir -p "$hacs_dir"
    rm -rf "$hacs_dir"/*

    if curl --retry 5 --retry-connrefused -C - -L -o "${hacs_dir}hacs.zip" "$hacs_url"; then
        cd "$hacs_dir" && unzip -oq hacs.zip && rm -f hacs.zip
        docker restart homeassistant
        echo "HACS installed successfully!"
    else
        echo "[ERROR] Failed to download HACS package."
    fi
}

if curl -s --max-time 3 https://version.hasscn.top/online.txt >/dev/null; then
    hacs >/dev/null 2>&1 &
else
    if [ ! -f /mnt/data/supervisor/homeassistant/custom_components/hacs/base.py ]; then
        hacs >/dev/null 2>&1 &
    fi
fi


docker container exec \
    -ti hassio_cli \
    /usr/bin/cli.sh

case $? in
  10)
    # Jump to root login shell (login command)
    exec /bin/ash -l
    ;;
  143)
    # 143 graceful termination (SIGTERM). Most likely a proper shutdown.
    # Just sleep for a while until actual systemd shutdown gets invoked.
    echo ""
    echo "Home Assistant CLI has been terminated."
    sleep 30
    ;;
  *)
    echo "HA CLI failed with error code: $?"
    ;;
esac
